// File generated by flutterfire_cli. Manually created due to CLI timeout.
// This file can be regenerated by running: flutterfire configure --project=amrutha-academy

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGEVaNOr5hqLGZPBf2TBonnEPnG5n_Sw0',
    appId: '1:960116742735:web:b095cde08c62ce4ab5e83a',
    messagingSenderId: '960116742735',
    projectId: 'amrutha-cademy',
    authDomain: 'amrutha-cademy.firebaseapp.com',
    storageBucket: 'amrutha-cademy.firebasestorage.app',
    measurementId: 'G-ES5JMYT86Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDziJoGcKBiY0zNXWekbFe6-n4Vz-mDDz8',
    appId: '1:960116742735:android:1370b4acee718025b5e83a',
    messagingSenderId: '960116742735',
    projectId: 'amrutha-cademy',
    storageBucket: 'amrutha-cademy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlmVr__lgcOI4PvCO8ESc9fF9S3XJHalg',
    appId: '1:960116742735:ios:885484616b94ac1fb5e83a',
    messagingSenderId: '960116742735',
    projectId: 'amrutha-cademy',
    storageBucket: 'amrutha-cademy.firebasestorage.app',
    iosBundleId: 'a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ1x6bwLTxKn3WGHtTc3ClD451JiSuciw',
    appId: '1:349596859394:ios:PLACEHOLDER_APP_ID',
    messagingSenderId: '349596859394',
    projectId: 'amrutha-academy',
    storageBucket: 'amrutha-academy.firebasestorage.app',
    databaseURL: 'https://amrutha-academy-default-rtdb.firebaseio.com',
    iosBundleId: 'com.amruthaacademy.amruthaAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ1x6bwLTxKn3WGHtTc3ClD451JiSuciw',
    appId: '1:349596859394:web:8038398eb110ef689c7b1b',
    messagingSenderId: '349596859394',
    projectId: 'amrutha-academy',
    authDomain: 'amrutha-academy.firebaseapp.com',
    storageBucket: 'amrutha-academy.firebasestorage.app',
    databaseURL: 'https://amrutha-academy-default-rtdb.firebaseio.com',
  );
}